# H2 - base de datos en memoria para desarrollo
spring.datasource.url=jdbc:h2:file:./data/hunterdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 ? puedes verla en http://localhost:8080/h2-console
spring.h2.console.enabled=true

telegram.bot.token=8642130234:AAElUu9YL7Vd2m85iZ9z0YzK5vMPpUNObB0
telegram.bot.chatId=8389147621